### ISSUE TITLE
plex/tautulli support?

### ISSUE THREAD

**Issue by kysersoze81** [p-hueber/prefetcharr#18]
What's the chances of adding in plex support or tautulli for tracking watched episodes?

**Comment by p-hueber** [comment]
@kysersoze81 I just pushed #19, it would be great to get some feedback on it before I merge this. I don't use plex myself, so it didn't get much testing.

**Comment by kysersoze81** [comment]
Just grabbed this now. (docker for testing)
Do we have any logging to verify that its working?

**Comment by p-hueber** [comment]
@kysersoze81 if you use the docker-compose example from the readme, just replace `#latest` with `#plex` and build the image again.
use the [server token](https://www.plexopedia.com/plex-media-server/general/plex-token/#plexservertoken) and make sure you got the url right - error reporting isn't ideal yet and an incorrect url goes unnoticed.

if everything is set up correctly, you should be able to see something like this in the logs if there's an active playback session
```
 INFO prefetcharr::process: title="The Bear" now_playing=NowPlaying { series: Tvdb(403294), episode: 1, season: 1 } 
```

**Comment by kysersoze81** [comment]
For some reason i can't seem to pull the #plex build
Docker version 26.0.0, build 2ae903e
Docker Compose version v2.26.0
I've had to modify the compose.yml to get it to work at all
```
name: prefetcharr
services:
    prefetcharr:
        build: https://github.com/p-hueber/prefetcharr.git#plex
        environment:
            - MEDIA_SERVER_TYPE=plex
            - MEDIA_SERVER_URL=http://local.ip.address.home
            - MEDIA_SERVER_API_KEY=redacted
            - SONARR_URL=http://lan.ip.address.home/sonarr
            - SONARR_API_KEY=redacted
            - LOG_DIR=/log
            - RUST_LOG=prefetcharr
            - INTERVAL=900
            - REMAINING_EPISODES=2
        volumes:
            - /home/prefetcharr:/log
        image: prefetcharr
```
