### ISSUE TITLE
Plex Session Problem

### ISSUE THREAD

**Issue by DerChris119** [p-hueber/prefetcharr#57]
Hello, 

i am so sry. But i cant get it to work. I think there is not much what i could do wrong. But i am looking so much forward for your Contributions so i ll have to ask again.

I think it gets a connection but i have this Error now:

```
2024-10-30T16:14:58.621361Z  INFO prefetcharr: prefetcharr 0.8.0

2024-10-30T16:14:58.623379Z  INFO prefetcharr: Start watching Plex sessions

2024-10-30T16:19:38.662780Z ERROR prefetcharr::media_server: cannot fetch sessions from media server: error sending request for url (http://x.x.x.x:32400/status/sessions)
```

Do you have an Idea?

**Comment by p-hueber** [comment]
Maybe temporary connection problems?
There's an initial connection check for Plex that would show a different error, so things seem to be fine at first. If you keep it running, does the error message repeat after your configured polling interval?

**Comment by DerChris119** [comment]
I turned down the Polling to 20 and is see nothing in the Log. Uselly there should be the Series that get watched. 

```      # Polling interval in seconds
      - INTERVAL=20 ```
      
      I mean even that the first Log shows after 5 min makes no sense when i have polling to 20s

**Comment by p-hueber** [comment]
> I mean even that the first Log shows after 5 min makes no sense when i have polling to 20s

That just means that requesting the session list from Plex takes 5 minutes until it ultimately fails. Sounds like some sort of timeout to me.
Try setting `RUST_LOG=trace` and attach the log as a file. Maybe we can learn more from that.

**Comment by DerChris119** [comment]
Thank you for you answer here is my Trace Log
[_prefetcharr_logs.txt](https://github.com/user-attachments/files/17579168/_prefetcharr_logs.txt)

**Comment by p-hueber** [comment]
Well there's no error in the log, so that's an improvement ;)
I think there's two things at play here.
The error in the log which seems like a networking error or maybe some rate-limiting feature of Plex? I'm not sure, but it still seems temporary to me.
And if I got that correctly, you don't get to see any playback sessions even in the absence of that error. I have reason to believe that this is a regression introduced by #52.

Could you please run an older version by replacing the `image` entry in your docker compose with `build: https://github.com/p-hueber/prefetcharr.git#0.7.4`? You'd need to run `docker compose build` to build the image.

**Comment by DerChris119** [comment]
Hello Hüber,

thank you again for your answer. My compose right now looks like this. 

```
prefetcharr:
    build: https://github.com/p-hueber/prefetcharr.git#0.7.4
    container_name: prefetcharr
    environment:
      - MEDIA_SERVER_TYPE=plex
      - MEDIA_SERVER_URL=http://plex:32400
      - MEDIA_SERVER_API_KEY=xxxxx
      - SONARR_URL=http://sonarr-1080p:8989
      - SONARR_API_KEY=xxxxxx
      - LOG_DIR=/log
      - RUST_LOG=trace
      - INTERVAL=20
      - REMAINING_EPISODES=2
    volumes:
      - /home/arr/prefetcharr:/log
    networks:
      rr_network:
        ipv4_address: 192.168.10.16
```

I allready tried without the User because some of my discord mates run this docker without them.

But i think with this Build Command Docker does not pull the right Image. In my Image Tab i only see these Images called like prefetcharr.

![image](https://github.com/user-attachments/assets/771ced47-3d76-4fd0-b609-e9bf307a62b0)
[_prefetcharr_logs.txt](https://github.com/user-attachments/files/17584658/_prefetcharr_logs.txt)


Regardless of that now its working i think. I get the same error but prefectharr does not Stop its Task. And it shows it gets the Session right this Time. 

Seems like its fixed? :)

Greetings Chris
