### ISSUE TITLE
Probing Jellyfin failed: error sending request for url (http://jellyfin:8096/System/Endpoint)

### ISSUE THREAD

**Issue by SkepticMystic** [p-hueber/prefetcharr#66]
Hi there,
I'm trying to get Prefetcharr setup and running. I get the following errors after brnging up the stack. Her'es my docker-compose.yml

```yaml
services:
  prefetcharr:
    image: phueber/prefetcharr:latest
    container_name: prefetcharr
    environment:
      - MEDIA_SERVER_TYPE=jellyfin
      - MEDIA_SERVER_URL=http://jellyfin:8096
      - MEDIA_SERVER_API_KEY=${JELLYFIN_API_KEY_PREFECTHARR}
      - SONARR_URL=http://sonarr:8989
      - SONARR_API_KEY=${SONARR_API_KEY}
      - LOG_DIR=/logs
      - RUST_LOG=prefetcharr=debug
      - INTERVAL=900
      - REMAINING_EPISODES=4
    volumes:
      - /opt/ezarr/config/prefetcharr/logs:/logs
    depends_on:
      - sonarr
      - jellyfin
```

I've not included the other containers in the stack, but the jellyfin endpoint works fine for other services like jellystat or jellyseer.

Please let me know if there's more info I can provide
